#!/bin/sh
# Dependencies: 
#               https://github.com/Rabcor/scriptdump/blob/main/spammouse
#               https://github.com/Rabcor/scriptdump/blob/main/spamkey
#               sxhkd
#               xdotool

device=$1
mode=$2
event=$3

scriptpath="~/Scripts"
mousescriptname=spammouse
kbdscriptname=spamkey

restartsxhkd=n  # set to y if you want to restart sxhkd after running 'spamsxhkd -c'

confdir="/home/$USER/.config/sxhkd"

if [ "$1" = "-c" ]; then
    rm $confdir/spamsxhkdrc_* &> /dev/null
    killall -u $USER sxhkd &
    pkill $mousescriptname &
    pkill $kbdscriptname &

    if [ "$restartsxhkd" = "y" ]; then
        sleep 0.1
        sxhkd &
    fi

    exit
fi

# Ensure syntax is correct, display help and exit if it is not.
if [ "$device" != "-m" ] && [ "$device" != "-k" ] || [ "$mode" != "-h" ] &&  [ "$mode" != "-t" ] || [ "$event" = "" ]; then
    echo "Syntax: spamsxhkd [Device Arg] [Mode Arg] [Event]
Example: spamsxhkd -m -h 1

Device Arguments:
    -m          Mouse
    -k          Keyboard

Mode Arguments:
    -h          Hold mode
    -t          Toggle mode

Mouse Events:
    [Button ID] Mouse buttons are represented by integers, use xev to find button ID

Keyboard Events:
    [Keysym]    Keysym for the key you want to spam, use xev to find keysyms

Other Arguments:
    -c          Kill sxhkd and clean up files
    "
    exit
fi


case $device in
    "-m")
        button="button$event"
        case $mode in
            "-t")
                echo "$button
    $scriptpath/$mousescriptname $event
                " > $confdir/spamsxhkdrc_m_$event
                ;;
            "-h")
                echo "$button
    $scriptpath/$mousescriptname $event
@$button
    $scriptpath/$mousescriptname $event
                " > $confdir/spamsxhkdrc_m_$event
                ;;
        esac
        sxhkd -c $confdir/spamsxhkdrc_m_$event
        ;;
    "-k")
        case $mode in
            "-t")
                echo "$event
    $scriptpath/$mousescriptname $event
                " > $confdir/spamsxhkdrc_k_$event
                ;;
            "-h")
                echo "$event
    $scriptpath/$mousescriptname $event
@$event
    $scriptpath/$mousescriptname $event
                " > $confdir/spamsxhkdrc_k_$event
                ;;
        esac
        sxhkd -c $confdir/spamsxhkdrc_m_$event
        ;;
esac
