#!/bin/sh
#This script binds WASD to behave as the Arrow keys when activated, and resets your keyboard bindings when activated again.

if xmodmap -pke | grep "  25" | grep Up ; then
	echo "Resetting Keybinds to default."
	setxkbmap # Reset keybinds
	xmodmap ~/.Xmodmap # Reloads default xmodmap settings
else
	echo "Binding WASD to behave like the Arrow keys."
	xmodmap -e "keycode 25 = Up" # w => Up
	xmodmap -e "keycode 38 = Left" # a => Left
	xmodmap -e "keycode 39 = Down" # s => Down
	xmodmap -e "keycode 40 = Right" # d => Right
fi
